### PR TITLE
I think it works for real this time.

### PR DESCRIPTION
**Pull request by ztlawton**

### CODE REVIEW

**Review by JamesBremner — CHANGES_REQUESTED** [review]
This is wrong.  

You are constructing a stringstream object, populating it with the name, then allowing it to do out of scope and be deleted without doing anything with it.  What did you intend to do with this?

**Comment by JamesBremner** [comment]
You are creating a separate commit for each file. Please do not do that - it makes it very hard to review your pull request.

Your workflow should go something like this:

- Make changes to your files, using VSCODE or another IDE
- Build and test your changes
- If tests go OK, THEN you commit ALL the changed files in ONE commit
- Post a pull request.

**Comment by ztlawton** [comment]
Ah. I've been editing the files in GitHub, in the browser.

I added the stringstream object and name for the Workshops since you had added it for the Modules. I can take it out, though.

**Comment by JamesBremner** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

NEVER NEVER NEVER NEVER merge your code into someone else's repository.

You must wait for your pull request to be approved and then the repository owner will do the merge.

How would you feel if I dumped some random code into your repository?  Well, that is how I feel

**Comment by JamesBremner** [comment]
I have removed your unapproved pull merge

**Comment by JamesBremner** [comment]
As I mentioned before, your pull request is very hard to review because it is broken up into tiny little commits one file at a time.

I cannot be certain, but it looks like you have ignored https://github.com/JamesBremner/workshoplocator/issues/2#issuecomment-1510422566

When I take a look at your repository ( https://github.com/ztlawton/workshoplocator/blob/b9a9bf3c9a140433714a0aab5eedd129b144c32b/src/main.cpp#L222 ) the problem is still there.

This should throw an exception when you run the program.  Did you run the program before committing?

**Comment by ztlawton** [comment]
I'm sorry, I'm getting lost between all the separate threads. I ran starter and didn't see any error messages, so I thought it was working.

How do I keep the files on my computer in sync with the files on GitHub, and push changes on my computer up to GitHub? I'm not finding the UI intuitive, and the results that come from Googling are going over my head.

**Comment by ztlawton** [comment]
I feel like I'm missing a lot of background knowledge that the tutorials are assuming I already know. Like how I'd never heard of PATH and thus misunderstood what you were asking me to do.

**Comment by ztlawton** [comment]
Each question I do a Google search for brings up more things I don't understand and have to Google in turn. Fractal/recursive research.

**Pull request merged**
